name: Check Markdown links

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      # Sub repos will not be checked.
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
